spring:
  application:
    name: expense-tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/expense_tracker
    username: postgres
    password: root
    driver-class-path : org.postgresql.driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: HikariPool-1
      max-lifetime: 1800000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://127.0.0.1:7080/realms/master/protocol/openid-connect/certs"

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: transaction-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"   # or your package

    listener:
      ack-mode: record
server:
  port: 9090

